#!/usr/bin/env perl
use Mojolicious::Lite;

use lib 'lib';
use MyLDAP;

# create a LDAP session
my $ldap = MyLDAP->new();

get '/' => sub {
  my $self = shift;
  $self->render('index');
};


post '/login' => sub {
    my $self = shift;
    my $username = $self->param('uid') || '';
    my $password = $self->param('pw') || '';
   
    $self->render(text => "Wrong username or password") 
	if !$ldap->pw_ok($username, $password);

    if ($ldap->is_admin($username)) {
	$self->render('admin');
    } else {
	$self->render('user');
    }
};

get '/reset' => sub { shift->render('reset') };

get '/send_reset_email' => sub {
    my $self = shift;
    $self->render_text("sending email");
};


app->start;

__DATA__

@@ index.html.ep
% layout 'default';
% title 'User admin';
<h2>Welcome to User admin!</h2>
%= form_for '/login' => (method => 'post' ) => begin
  User name: 
  %= text_field 'uid'
  <br>
  Password:
  %= password_field 'pw'
  <br>
  %= submit_button "Login"
  <br>
  %= link_to "I've forgotten my username or password" => 'reset'
% end


@@ reset.html.ep
    % layout 'default';
% title 'Reset password';
<h2>Enter the email address used when registering</h2>
%= form_for 'send_reset_email' => (method =>  'post') => begin
    Email address:
    %= text_field 'email'
    @ventelo.no
    <br>
    %= submit_button "Send"
% end


@@ admin.html.ep
    % layout 'default';
% title  'Admin';
    <h2>Administer users</h2>
    This is the place to administer all users

@@ user.html.ep
    % layout 'default';
% title  'Users';
    <h2>User self service</h2>
    This is the place to administer your profile


@@ layouts/default.html.ep
<!doctype html><html>
  <head><title><%= title %></title></head>
  <body><%= content %></body>
</html>
